# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.5"
  - "3.6"
  #- "3.5-dev" # 3.5 development branch
  #- "nightly" # points to the latest development branch e.g. 3.6-dev
# command to install dependencies
install: "pip install -r requirements.txt -r test-requirements.txt"
# command to run tests
script: pytest --verbose --cov=management_layer management_layer/
